# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "user",
  "following",
  "message"
]

const attributes = [
  Attr(name: "username", tabIndex: 0, typ: dbVarchar, key: 1),
  Attr(name: "follower", tabIndex: 1, typ: dbVarchar, key: -1),
  Attr(name: "followed_user", tabIndex: 1, typ: dbVarchar, key: -1),
  Attr(name: "username", tabIndex: 2, typ: dbVarchar, key: -1),
  Attr(name: "time", tabIndex: 2, typ: dbInt, key: 0),
  Attr(name: "msg", tabIndex: 2, typ: dbVarchar, key: 0)
]
