# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
const tableNames = [
  "users",
  "messages"
]

const attributes = [
  Attr(name: "id", tabIndex: 0, typ: dbInt, key: 1),
  Attr(name: "name", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "password", tabIndex: 0, typ: dbVarchar, key: 0),
  Attr(name: "creation", tabIndex: 0, typ: dbTimestamp, key: 0),
  Attr(name: "lastonline", tabIndex: 0, typ: dbTimestamp, key: 0),
  Attr(name: "id", tabIndex: 1, typ: dbInt, key: 1),
  Attr(name: "author", tabIndex: 1, typ: dbInt, key: -1),
  Attr(name: "content", tabIndex: 1, typ: dbVarchar, key: 0),
  Attr(name: "creation", tabIndex: 1, typ: dbTimestamp, key: 0)
]
