import std/[macros, strutils, tables]
import db_connector/db_common

import ./db_types
import ./parsesql_tmp

const
  FileHeader* = """
# Generated by ormin_importer. DO NOT EDIT.

type
  Attr = object
    name: string
    tabIndex: int
    typ: DbTypekind
    key: int   # 0 nothing special,
               # +1 -- primary key
               # -N -- references attribute N
"""

type
  DbColumn* = object
    name*: string
    tableName*: string
    typ*: DbType
    primaryKey*: bool
    refs*: (string, string)
  DbColumns* = seq[DbColumn]

  KnownTables* = OrderedTable[string, DbColumns]
  KnownEnums = Table[string, seq[string]]
  ImportTarget* = enum
    postgre, sqlite, mysql

proc hasAttribute(colDesc: SqlNode; k: set[SqlNodeKind]): bool =
  for i in 2 ..< colDesc.len:
    if colDesc[i].kind in k:
      return true

proc hasRefs(colDesc: SqlNode): (string, string) =
  for i in 2 ..< colDesc.len:
    let c = colDesc[i]
    if c.kind == nkReferences:
      if c[0].kind == nkColumnReference:
        return (sqlIdentBaseName(c[0][0]), sqlIdentBaseName(c[0][1]))
      elif c[0].kind == nkCall:
        return (sqlIdentBaseName(c[0][0]), sqlIdentBaseName(c[0][1]))
      elif c[0].kind in {nkIdent, nkQuotedIdent, nkDot}:
        return (sqlIdentBaseName(c[0]), "id")
  ("", "")

proc isSqlIdentChar(c: char): bool =
  c in {'a'..'z', 'A'..'Z', '0'..'9', '_', '$'}

proc skipSqlTrivia(sql: string; pos: var int) =
  var keepReading = true
  while keepReading and pos < sql.len:
    keepReading = false
    while pos < sql.len and sql[pos] in Whitespace:
      inc pos
      keepReading = true
    if pos + 1 < sql.len and sql[pos] == '-' and sql[pos + 1] == '-':
      inc pos, 2
      while pos < sql.len and sql[pos] notin {'\c', '\L'}:
        inc pos
      keepReading = true
    elif pos + 1 < sql.len and sql[pos] == '/' and sql[pos + 1] == '*':
      inc pos, 2
      while pos + 1 < sql.len and not (sql[pos] == '*' and sql[pos + 1] == '/'):
        inc pos
      if pos + 1 < sql.len:
        inc pos, 2
      keepReading = true

proc consumeSqlKeyword(sql: string; pos: var int; keyword: string): bool =
  skipSqlTrivia(sql, pos)
  let finish = pos + keyword.len
  if finish > sql.len:
    return false
  if cmpIgnoreCase(sql[pos ..< finish], keyword) != 0:
    return false
  if finish < sql.len and isSqlIdentChar(sql[finish]):
    return false
  pos = finish
  true

proc readSqlIdentPart(sql: string; pos: var int): string =
  skipSqlTrivia(sql, pos)
  if pos >= sql.len:
    return ""

  if sql[pos] == '"':
    inc pos
    while pos < sql.len:
      if sql[pos] == '"':
        if pos + 1 < sql.len and sql[pos + 1] == '"':
          result.add('"')
          inc pos, 2
        else:
          inc pos
          return
      else:
        result.add(sql[pos])
        inc pos
  else:
    while pos < sql.len and isSqlIdentChar(sql[pos]):
      result.add(sql[pos])
      inc pos

proc readSqlQualifiedIdent(sql: string; pos: var int): string =
  result = readSqlIdentPart(sql, pos)
  if result.len == 0:
    return

  while true:
    let beforeDot = pos
    skipSqlTrivia(sql, pos)
    if pos >= sql.len or sql[pos] != '.':
      pos = beforeDot
      return
    inc pos
    let part = readSqlIdentPart(sql, pos)
    if part.len == 0:
      return
    result.add('.')
    result.add(part)

proc readSqlStringLiteral(sql: string; pos: var int): string =
  skipSqlTrivia(sql, pos)
  if pos >= sql.len or sql[pos] != '\'':
    return ""

  inc pos
  while pos < sql.len:
    if sql[pos] == '\'':
      if pos + 1 < sql.len and sql[pos + 1] == '\'':
        result.add('\'')
        inc pos, 2
      else:
        inc pos
        return
    else:
      result.add(sql[pos])
      inc pos

proc readSqlEnumValues(sql: string; pos: var int): seq[string] =
  skipSqlTrivia(sql, pos)
  if pos >= sql.len or sql[pos] != '(':
    return @[]
  inc pos

  var done = false
  while not done and pos < sql.len:
    skipSqlTrivia(sql, pos)
    if pos < sql.len and sql[pos] == ')':
      inc pos
      done = true
    else:
      let value = readSqlStringLiteral(sql, pos)
      if value.len == 0:
        done = true
      else:
        result.add(value)
        skipSqlTrivia(sql, pos)
        if pos < sql.len and sql[pos] == ',':
          inc pos
        elif pos < sql.len and sql[pos] == ')':
          inc pos
          done = true
        else:
          done = true

proc registerEnum(enums: var KnownEnums; typeName: string; values: seq[string]) =
  if typeName.len == 0 or values.len == 0:
    return

  let normalized = typeName.toLowerAscii
  enums[normalized] = values
  let dotPos = normalized.rfind('.')
  if dotPos >= 0 and dotPos + 1 < normalized.len:
    enums[normalized[dotPos + 1 .. ^1]] = values

proc collectEnumTypes(schemaSql: string): KnownEnums =
  result = initTable[string, seq[string]]()
  let lowerSql = schemaSql.toLowerAscii
  var searchFrom = 0
  while searchFrom < lowerSql.len:
    let found = lowerSql.find("create type", searchFrom)
    if found < 0:
      break

    var pos = found
    if consumeSqlKeyword(schemaSql, pos, "create") and
        consumeSqlKeyword(schemaSql, pos, "type"):
      let beforeOptional = pos
      if consumeSqlKeyword(schemaSql, pos, "if"):
        if not consumeSqlKeyword(schemaSql, pos, "not") or
            not consumeSqlKeyword(schemaSql, pos, "exists"):
          pos = beforeOptional

      let typeName = readSqlQualifiedIdent(schemaSql, pos)
      if consumeSqlKeyword(schemaSql, pos, "as") and
          consumeSqlKeyword(schemaSql, pos, "enum"):
        result.registerEnum(typeName, readSqlEnumValues(schemaSql, pos))
      searchFrom = max(pos, found + 1)
    else:
      searchFrom = found + 1

proc getType(n: SqlNode; enums: KnownEnums): DbType =
  var it = n
  if it.kind == nkCall:
    it = it[0]
  if it.kind == nkEnumDef:
    result.kind = dbEnum
    result.validValues = @[]
    for i in 0 ..< it.len:
      assert it[i].kind == nkStringLit
      result.validValues.add it[i].strVal
  elif it.kind in {nkIdent, nkQuotedIdent, nkStringLit, nkDot}:
    let typeName = sqlIdentName(it)
    let normalized = typeName.toLowerAscii
    if enums.hasKey(normalized):
      result.kind = dbEnum
      result.validValues = enums[normalized]
    else:
      let baseName = sqlIdentBaseName(it)
      result.kind = dbTypFromName(baseName)
    result.name = typeName

proc collectTables*(n: SqlNode; t: var KnownTables; enums: KnownEnums) =
  if n.isNil:
    return
  case n.kind
  of nkCreateTable, nkCreateTableIfNotExists:
    let tableName = sqlIdentBaseName(n[0])
    var cols: DbColumns = @[]
    for i in 1 ..< n.len:
      let it = n[i]
      if it.kind == nkColumnDef:
        var typ = getType(it[1], enums)
        if hasAttribute(it, {nkNotNull}):
          typ.notNull = true
        cols.add DbColumn(
          name: it[0].strVal,
          tableName: tableName,
          typ: typ,
          primaryKey: hasAttribute(it, {nkPrimaryKey}),
          refs: hasRefs(it)
        )
    for i in 1 ..< n.len:
      let it = n[i]
      if it.kind == nkForeignKey:
        var refNode: SqlNode = nil
        var localCols: seq[string] = @[]
        for j in 0 ..< it.len:
          let child = it[j]
          if child.kind == nkReferences:
            refNode = child
          elif child.kind == nkIdent:
            localCols.add(child.strVal)
        if refNode.isNil:
          continue
        var r = refNode[0]
        var refTable = ""
        var refCols: seq[string] = @[]
        if r.kind == nkColumnReference or r.kind == nkCall:
          refTable = sqlIdentBaseName(r[0])
          for k in 1 ..< r.len:
            refCols.add(sqlIdentBaseName(r[k]))
        let pairCount = min(localCols.len, refCols.len)
        for k in 0 ..< pairCount:
          let localName = localCols[k]
          let targetCol = refCols[k]
          for c in mitems(cols):
            if cmpIgnoreCase(c.name, localName) == 0:
              c.refs = (refTable, targetCol)
              break
    t[tableName] = cols
  else:
    for i in 0 ..< n.len:
      collectTables(n[i], t, enums)

proc attrToKey(a: DbColumn; t: KnownTables): int =
  if a.primaryKey:
    return 1
  if a.refs[0].len > 0:
    var i = 0
    for k, v in pairs(t):
      for b in v:
        if cmpIgnoreCase(k, a.refs[0]) == 0 and cmpIgnoreCase(b.name, a.refs[1]) == 0:
          return -i - 1
        inc i
  0

proc renderModelCode(schemaSql, schemaPath: string; target: ImportTarget; includeStatic = false): string =
  discard target
  let sql = parseSql(schemaSql, schemaPath)
  let enums = collectEnumTypes(schemaSql)
  var knownTables = initOrderedTable[string, DbColumns]()
  collectTables(sql, knownTables, enums)

  result.add FileHeader
  result.add "const tableNames = ["
  var i = 0
  for k in keys(knownTables):
    if i > 0:
      result.add ",\n  "
    else:
      result.add "\n  "
    result.add escape(k.toLowerAscii)
    inc i
  result.add "\n]\n"

  i = 0
  var j = 0
  result.add "\nconst attributes = ["
  for _, v in mpairs(knownTables):
    for a in v:
      if j > 0:
        result.add ",\n  "
      else:
        result.add "\n  "
      result.add "Attr(name: "
      result.add escape(a.name.toLowerAscii)
      result.add ", tabIndex: "
      result.add $i
      result.add ", typ: "
      result.add $a.typ.kind
      result.add ", key: "
      result.add $attrToKey(a, knownTables)
      result.add ")"
      inc j
    inc i
  result.add "\n]\n"

  if includeStatic:
    result.add "\nconst sqlSchema* = staticLoad("
    result.add escape(schemaPath)
    result.add ")\n"

proc generateModelCode*(schemaSql, schemaPath: string; target: ImportTarget; includeStatic = false): string =
  renderModelCode(schemaSql, schemaPath, target, includeStatic)

macro generateModelCode*(schemaSql: static[string], schemaPath: static[string],
                         target: static[ImportTarget], includeStatic: static[bool] = false): untyped =
  parseStmt(renderModelCode(schemaSql, schemaPath, target, includeStatic))
